### ISSUE TITLE
Support for torchaudio wheels

### ISSUE THREAD

**Issue by CubeSkyy** [evshiron/rocm_lab#1]
I was able to run Tensorflow, Torch and TorchVision with the latest release. However, Im currently trying to run a project that uses a fork of [neonbjb/tortoise-tts](https://github.com/neonbjb/tortoise-tts) which requires torchaudio. I tried installing the provided .whl for torch and torchvision and install torchaudio afterwards, but I'm getting an error while importing torchaudio:
`OSError: libtorch_cuda.so: cannot open shared object file: No such file or directory`

I assume this is because torchaudio version was not built along the custom torch/torchvision. 

Do you have any plans on making a guide using torchaudio?

Also, thank you so much for the work on the TF/Torch changes!

**Comment by evshiron** [comment]
Hi, I am busy at the moment and if you are in a hurry, you can try building it like `torchvision` by yourself:

If you already have ROCm 5.5 installed, skipping `scripts/prepare.sh` should be totally fine.

Then you can modify `scripts/build_torchvision.sh`, replace `torchvision` stuff with `torchaudio`, run it and see if it compiles. The built wheels should be located in the `dist` dir.

I will experiment with it later and eventually have a GitHub workflow for it.

UPDATE: It's not as easy as I thought, will be back later.

**Comment by CubeSkyy** [comment]
I'm not in a hurry, I will try to compile it and test If I have time. Thank you for the reply,

**Comment by evshiron** [comment]
`torchaudio==2.0.2` is now available in [this workflow](https://github.com/evshiron/rocm_lab/actions/workflows/build-rocm5.5-torchaudio2.0-wheels.yaml), and will be moved to GitHub Releases once verified.

**Comment by evshiron** [comment]
I managed to generate voices using [neonbjb/tortoise-tts](https://github.com/neonbjb/tortoise-tts), here is how:

```bash
git clone https://github.com/neonbjb/tortoise-tts
cd tortoise-tts

python3 -m venv venv
source venv/bin/activate

curl -L -O https://github.com/evshiron/rocm_lab/releases/download/v1.14.514/torch-2.0.1+gite19229c-cp310-cp310-linux_x86_64.whl
pip install torch-2.0.1+gite19229c-cp310-cp310-linux_x86_64.whl

curl -L -O https://github.com/evshiron/rocm_lab/releases/download/v1.14.514/torchaudio-2.0.2+31de77d-cp310-cp310-linux_x86_64.whl
pip install torchaudio-2.0.2+31de77d-cp310-cp310-linux_x86_64.whl
```

I am using Python 3.10.6 and I have to edit `requirements.txt` like this to avoid a lot of compiling from source (don't do this if you know how to do it correctly):

```
diff --git a/requirements.txt b/requirements.txt
index c1846c9..0babe68 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -6,13 +6,11 @@ inflect
 progressbar
 einops==0.4.1
 unidecode
-scipy==0.10.1
+scipy
 librosa==0.9.1
-numba==0.48.0
+numba
 ffmpeg
-numpy==1.20.0
-numba==0.48.0
-torchaudio
+numpy
 threadpoolctl
 llvmlite
-appdirs
\ No newline at end of file
+appdirs

```

Install [neonbjb/tortoise-tts](https://github.com/neonbjb/tortoise-tts) into venv:

```bash
pip install -r requirements.txt
python3 setup.py install
```

Generate voices:

```bash
python3 tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
```

The results will be located in the `results` dir.

Samples: [results.zip](https://github.com/evshiron/rocm_lab/files/11521830/results.zip)

**Comment by CubeSkyy** [comment]
Thank you so much!
