### ISSUE TITLE
7900xtx get confused sdpa result

### ISSUE THREAD

**Issue by sdli1995** [evshiron/rocm_lab#5]
benchmark use pytorch function is slow but if timeit use system function is faster

code like this 

```
import time 
import torch
import torch.nn as nn
import torch.nn.functional as F
device = "cuda" if torch.cuda.is_available() else "cpu"

# Lets define a helpful benchmarking function:
import torch.utils.benchmark as benchmark
def benchmark_torch_function_in_microseconds(f, *args, **kwargs):
    t0 = benchmark.Timer(
        stmt="f(*args, **kwargs)", globals={"args": args, "kwargs": kwargs, "f": f}
    )
    return t0.blocked_autorange().mean * 1e6

# Lets define the hyper-parameters of our input
batch_size = 32
max_sequence_len = 1024
num_heads = 40
embed_dimension = 128

dtype = torch.float16

query = torch.rand(batch_size, num_heads, max_sequence_len, embed_dimension, device=device, dtype=dtype)
key = torch.rand(batch_size, num_heads, max_sequence_len, embed_dimension, device=device, dtype=dtype)
value = torch.rand(batch_size, num_heads, max_sequence_len, embed_dimension, device=device, dtype=dtype)

# Helpful arguments mapper

print(f"The default implementation runs in {benchmark_torch_function_in_microseconds(F.scaled_dot_product_attention, query, key, value):.3f} microseconds")

x = time.time()
for i in range(10):
    y = F.scaled_dot_product_attention(query, key, value)
    y = y.detach().cpu()
delta = time.time() - x
print('real exec time is',delta*1000, 'ms')
```

result in 3090 

```
The default implementation runs in 19356.447 microseconds
real exec time is 804.9180507659912 ms
```
result in rx7900xtx

```
The default implementation runs in 24952.195 microseconds
real exec time is 614.5007610321045 ms
```

**Comment by evshiron** [comment]
Greetings. Thank you for submitting the issue.

I am actually a layman in this area, and I just collect and compile information from the internet to make it more convenient for everyone to use. I don't have the resources to experiment across devices either.

Regarding performance issues, I think there is a lot of optimization space for the RX 7000 series, but I am in over my head and wanna suggest repos like [RadeonOpenCompute/ROCm](https://github.com/RadeonOpenCompute/ROCm) and [pytorch/pytorch](https://github.com/pytorch/pytorch) which should be more helpful.

**Comment by sdli1995** [comment]
> Greetings. Thank you for submitting the issue.
> 
> I am actually a layman in this area, and I just collect and compile information from the internet to make it more convenient for everyone to use. I don't have the resources to experiment across devices either.
> 
> Regarding performance issues, I think there is a lot of optimization space for the RX 7000 series, but I am in over my head and wanna suggest repos like [RadeonOpenCompute/ROCm](https://github.com/RadeonOpenCompute/ROCm) and [pytorch/pytorch](https://github.com/pytorch/pytorch) which should be more helpful.

I got it
