### ISSUE TITLE
use wheels on artix?

### ISSUE THREAD

**Issue by ewof** [evshiron/rocm_lab#6]
`ERROR: torch-2.0.1+gite19229c-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by evshiron** [comment]
Hmmm. Afaik Artix is an Arch distro and should not complain like this. Is your system `x86_64`? If it is, would you mind trying the Docker version [here](https://github.com/evshiron/rocm_lab#prebuilt-docker-images)?

Btw, there are issues like https://github.com/evshiron/rocm_lab/issues/3 and https://github.com/evshiron/rocm_lab/issues/4 occured on Arch distros as well, so I can't guarantee it will work.

**Comment by ewof** [comment]
i was bc i had python 3.11 i used python 3.10 and it worked fine
