### ISSUE TITLE
Any progress on Rocm 5.6 ?

### ISSUE THREAD

**Issue by sdli1995** [evshiron/rocm_lab#9]
Rocm 5.6 was Release but do not have a pytorch support

**Comment by evshiron** [comment]
Oh. I thought it should be compatible. I haven't upgraded to ROCm 5.6 yet, but will give it a try later today.

**Comment by evshiron** [comment]
The wheels are actually compatible with ROCm 5.6.

But when I build `torch` for ROCm 5.6 and use it, I get 10-20% extra performance in Stable Diffusion after it recompiles the kernels (when you generate, the progress bar freezes for a while, which happened to me previously when I upgraded ROCm from 5.5 to 5.5.1).

I am not sure whether a recompilation could be triggered with ROCm 5.6 and `torch` for ROCm 5.5 or not, so I am now building new `torch` wheels to make it happen easier.

The benchmark scores can be found here:

* https://vladmandic.github.io/sd-extension-system-info/pages/benchmark.html

**Comment by sdli1995** [comment]
Awesome job. I will try a train job in both rx7900xtx and rtx3090 with new wheel. later i will report the perfermance

**Comment by evshiron** [comment]
New wheels with proper versioning of `torch` and `torchvision` are now available in:

* https://github.com/evshiron/rocm_lab/releases/tag/rocm-5.6-builds

**Comment by sdli1995** [comment]
> New wheels with proper versioning of `torch` and `torchvision` are now available in:
> 
> * https://github.com/evshiron/rocm_lab/releases/tag/rocm-5.6-builds

ROCM 5.6 get obvious performance optimization. here is the results
```

ROCM-5.6 RX7900XTX FP32 trainning
mnasnet1_3	wide_resnet101_2	densenet201	squeezenet1_1	vgg19_bn	mobilenet_v3_small	shufflenet_v2_x2_0
49.30	120.61	100.98	21.38	80.56	29.16	34.37(ms)

ROCM-5.6 RX7900XTX FP16 trainning
mnasnet1_3	wide_resnet101_2	densenet201	squeezenet1_1	vgg19_bn	mobilenet_v3_small	shufflenet_v2_x2_0
36.63	65.02	99.76	13.42	45.97	18.67	26.72(ms)

CUDA12.1 RTX3090 FP32 trainning
mnasnet1_3	wide_resnet101_2	densenet201	squeezenet1_1	vgg19_bn	mobilenet_v3_small	shufflenet_v2_x2_0
21.26	89.88	82.73	8.91	67.24	15.20	25.33(ms)

CUDA12.1 RTX3090 FP16 trainning
mnasnet1_3	wide_resnet101_2	densenet201	squeezenet1_1	vgg19_bn	mobilenet_v3_small	shufflenet_v2_x2_0
17.41	53.22	87.04	8.13	41.34	14.00	20.37(ms)

ROCM-5.5 RX7900XTX FP32 trainning
mnasnet1_3	wide_resnet101_2	densenet201	squeezenet1_1	vgg19_bn	mobilenet_v3_small	shufflenet_v2_x2_0
81.08	397.09	220.07	39.68	336.59	41.94	46.08(ms)

ROCM-5.5 RX7900XTX FP16 trainning
mnasnet1_3	wide_resnet101_2	densenet201	squeezenet1_1	vgg19_bn	mobilenet_v3_small	shufflenet_v2_x2_0
41.30	93.46	186.49	17.88	69.28	27.49	33.38(ms)

```

**Comment by sdli1995** [comment]
transformer based model are not work well , waiting for new rocm

**Comment by evshiron** [comment]
Can you list some examples? I'd like to give it a try as well.

**Comment by sdli1995** [comment]
> Can you list some examples? I'd like to give it a try as well.

such as Transformer or Conformer CTC  (for speech recognition)  , those model throughout only 200-230 sample/s ,but 3090 is 800-900 sample/s
